### ISSUE TITLE
Session proposals

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conf#12]
Gather proposals for sessions to put in Day 1 (plenary) or Day 2 (multi-track). Primarily gather these proposals from Working Groups and maintainers. _This is separate from the Session Pitches for the Unconf on Day 3, though some stuff from this first round of proposals might get bumped to the unconf._

From those proposals we will select the sessions that can be pre-scheduled into Day 1 (plenary) or Day 2 (multi-track).

How should we collect these proposals? How should we solicit them from the community?

**Comment by hsanjuan** [comment]
cc @hsanjuan (I'll want to have a cluster session but I have to flesh out the topics in it)

**Comment by mgoelzer** [comment]
Plan is to have session submissions submitted as Issues in this repo.  @flyingzumwalt to create template and label.

**Comment by diasdavid** [comment]
From #40, the todo list is:

- [ ] create a template for session proposals
- [ ] post instructions for proposing sessions
- [ ] send out emails to all attendees about how to propose sessions
- [ ] send separate email to working group captains and people with KRs encouraging them to propose sessions

**Comment by meiqimichelle** [comment]
A link to proposing sessions was sent out to everyone in our original 'save the date', but it was among a lot of other info. May want to send a more pointed email with instructions, suggestions, etc, and/or do personal outreach to if there are specific people we have in mind.

**Comment by mgoelzer** [comment]
I'm going to do this for libp2p sessions.  (libp2p sessions are slightly
unique in that they are mandatory, but will be a mix of 3-5 lightning talks
for some plus longer content talks like on the new QUIC work for
high-interest topics.)  There should be a parallel solicitation for IPFS
sessions.

**Comment by diasdavid** [comment]
I'm proposing two new session formats to meet some of the objectives we have for this event and also to hit things we really need.

**Comment by mgoelzer** [comment]
Yes, I like your proposal in #43 a lot.  I'm going to do a PR now to update [libp2p/developer-meetings](https://github.com/libp2p/developer-meetings/issues)'s readme to have three participation options:  talk slots for stuff like QUIC (where I think there's high interest), poster teams, and protocol meetings (the last two as per your #43).

**Comment by diasdavid** [comment]
@mgoelzer @flyingzumwalt has there been any instructions sent to all the attendees with regards to the instructions? I believe that the low level of engagement in the Session PRs is correlated with the lack of information or simply missing action items.

**Comment by mgoelzer** [comment]
@diasdavid Let me know if you got my 6/27 email `Proposing & leading a session at libp2p Dev Meeting`?  That was sent to everyone attending libp2p DM, but if you don't remember receiving it then either it wasn't memorable/clear enough or something went wrong.

The process for libp2p is slightly different, the sessions are issues on https://github.com/libp2p/developer-meetings and the README of that repo explains the possible formats (protocol design, poster creation, presentation).

Is the engagement on https://github.com/libp2p/developer-meetings/issues lower than what you'd expect at this point?  Who could I reach out to for more ideas on topics?  (esp for protocol design discussion; that one seems most fruitful)

**Comment by diasdavid** [comment]
> Is the engagement on https://github.com/libp2p/developer-meetings/issues lower than what you'd expect at this point?

Both IPFS and libp2p issues show low engagement atm. Note that we have 300+ active participants in our repos (given Github stats) and 70 of which will be attending. Right now we have less than 8 people interacting or have proposed a session. It is really low.
