### ISSUE TITLE
Post an Online Event Schedule

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conf#15]
Objective: Provide an up-to-date online representation of the event schedule that people can rely on. 

It should:
- include information about session titles, descriptions, presenters, times and locations 
- be mobile friendly
- be easy to update if the schedule changes (though we will try to minimize changes)
- ideally also accommodate the unconference sessions on Day 3, which will be pitched & voted on at the end of Day 2 and set into a schedule that evening

Some options:
- Use [sessionizer](https://github.com/minnestar/sessionizer) - includes ways for proposing sessions and renders the final schedule like the [minnestar sessions list](https://sessions.minnestar.org/)
- Use a google spreadsheet
- Use [Sched](https://sched.com/)
- others?

**Comment by LorenzoPilia** [comment]
I've used Sched several times, I think it's one of the best solutions available to present and manage schedules online, but in our case the cost would be $500: https://sched.com/pricing

Google spreadsheet does the job, but it's not very practical / easy to read on mobile, particularly if sessions descriptions are included.

**Comment by meiqimichelle** [comment]
Discussion in meeting: we should set this up to see the admin view. We don't pay until live.

**Comment by LorenzoPilia** [comment]
I've set up the Sched account, populated it with some basic sessions and made Jamie, Matt, Michael, Michelle admins, so you can see the preview.

**Comment by diasdavid** [comment]
It's aaaliiiiive [**SCHEDULE**](https://developersmeetingsberlin2018.sched.com/)
