### ISSUE TITLE
Define printed paper and signage needs

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conf#16]
Define printed paper needs and signage 

Skylar and Jamie to define printed paper needs and signage by **Wednesday, May 16th**. 

Questions:
- Do we want printed itineraries?
  - A: Yes.
- Will we want banners and standing posters?
  - A: probably?
- Registration Table Banner?
  - A: sure.
- Stage standing sign?
  - A: most likely yes, to get the branding into recordings of the event

**Comment by flyingzumwalt** [comment]
Waiting on a final logo from https://github.com/ipfs/conference/issues/33

**Comment by flyingzumwalt** [comment]
Also think about lanyard design. @flyingzumwalt has thoughts. need to add them.

**Comment by mgoelzer** [comment]
Include 1 notebook + pen for each attendee.  Does not need to be branded - just something to give them when they register so they can write.
