### ISSUE TITLE
IPFS Website Discussion Doc.

### ISSUE THREAD

**Issue by fcbaila** [ipfs/conf#23]
Hi everyone, we are putting our deliverables in this doc:
https://docs.google.com/document/d/1X2HKFq_4xy0wGnlgL_NzqeC_exHTHx6YvpxmNUftguk/edit?usp=sharing

**Comment by meiqimichelle** [comment]
Update: the content and information architecture part of the deliverables doc has now been split into its own issue and documents in #34 . 

I hope to have the remaining deliverable points separated into their own issues soon as well so we can track each separately and close as we complete. I'll return here and update/close this issue as needed.
