### ISSUE TITLE
List of PL Attendees / Helpers

### ISSUE THREAD

**Issue by colinevran** [ipfs/conf#29]
@flyingzumwalt Not sure if there's an issue for this but creating a list of Core folks who will be available to join / help for the conference.

I can be there and arrive early to help organize / set up / do anything to help.

**Comment by miyazono** [comment]
I'd love to help with the summit or the conf as well.  It'd give me a good excuse to go and get more IPFS exposure when I'm not really involved enough in IPFS to merit being there.

**Comment by mgoelzer** [comment]
We're keeping a running list here: 
 https://docs.google.com/document/d/1wDyGcCOOSofT9rXqx0DUgV62bUpN0_GXvuVC2Pj-jeo/edit#heading=h.lfmf619pmawi

**Comment by colinevran** [comment]
@mgoelzer didn't see an explicit list in the doc, can you specify where we should put our names? 

I saw a link to this excel sheet but it looks like it was deleted: https://docs.google.com/spreadsheets/d/1rrHD4fLlPIyLgGjmHotoWLbKHbESfaKHZQP2DUBAt1Q/edit#gid=0

**Comment by mgoelzer** [comment]
@colinevran [This doc](https://docs.google.com/document/d/1wDyGcCOOSofT9rXqx0DUgV62bUpN0_GXvuVC2Pj-jeo/edit#heading=h.lfmf619pmawi) => go to heading **Things Helpers can Be In Charge Of**

(For some reason, I'm not able to recreate the anchor in that doc so the link clicks through to it immediately, but section is still there.)

**Comment by colinevran** [comment]
Signed up - thank you @mgoelzer !
