### ISSUE TITLE
Reserve room blocks in 2 Hotels 

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conf#3]
Reserve room blocks in 2 hotels near the venue -- one budget option and one more premium option.

_Note: We know that PL people will probably want to stay in an Airbnb. That's fine. The events team will help with that for PL people if they want, but putting all attendees in Airbnbs is too much overhead._

Blocked by #2 and #1 (nail down dates and venue)

**Comment by jamiejn** [comment]
Proposed dates of room blocks for attendees are Sunday, July 8th - Saturday, July 14th. 

Some PL staff and helpers will need to arrive earlier (July 6th or 7th) to prepare for the event.

[Hotel Proposals Spreadsheet](https://docs.google.com/spreadsheets/d/1_vtNEJAR3sJCS1qz0-T_GdNkTsynMxtPdWINqVHi9Xk/edit?usp=sharing)
