### ISSUE TITLE
Scholarships & Financial Assistance 

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conf#31]
The Dev Meeting application includes a section for requesting financial assistance. How will we decide who receives assistance?

Acceptance to the event should be need-blind, with evaluation of scholarships/assistance happening as a separate second step.

**Comment by flyingzumwalt** [comment]
We will look at the aggregate needs after applications close on May 28th and assess our budget vs needs/requests.

**Comment by meiqimichelle** [comment]
I moved this issue to the dev meetings repo [here](https://github.com/protocol/2018-dev-meetings-berlin/issues/27). Closing.
