### ISSUE TITLE
Design Visual Identity for IPFS Conf & Developer Meetings

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conf#33]
_This is consolidating and re-focusing work that @akrych did in another repository over the past few weeks. Our needs have evolved slightly and @meiqimichelle has helped me clarify the design objectives. Here is the updated design request._

We are asking @akrych to design two things:
1. A visual identity (logo, color palette) for IPFS Conf
2. A related but distinct visual identity for the IPFS and libp2p Developer Meetings

If we have separate logos for the Conf and the Developer Meetings, the Conf should be the dominant identity that catches people's attention. By contrast, the Developers Meetings will be the understated, practical, "internal" event so the branding should be understated too. For example, the website will have info about both events, but will feature the Conf much more prominently while requiring people to specifically seek out info about the Developers Meeting.

## IPFS Conf Visual Identity

- Priority is to have an identity for 2018 Conf, but if it can be re-used in future years that would be nice.
- emphasize ideas of community, shared enthusiasm, sharing information, working together
- we will probably have a tag line like "building the decentralized web together" or "making the web faster, safer and more open" (see https://github.com/ipfs/conference/issues/30)

## Developer Meetings visual identity
We are convening an IPFS Developer Meeting and a libp2p Developer Meeting. 

- We want some way to make documents, web pages, and information about the Developer Meetings visually distinct from info about IPFS Conf. For example, it should be easy to know if I'm looking at the venue & location details for IPFS Conf vs the Developer Meetings. 
- We don't necessarily need logos for the Dev Meetings, but logos would be nice. If you do create logos, we will probably use them for future working meetings. Future meetings won't necessarily be called "Developer Meetings" -- we might change the name -- but they will still be working meetings for contributors & maintainers, so avoid using "developer meeting" in the logo itself.
- The libp2p meeting is a distinct meeting from the  IPFS meeting -- different, but overlapping, participants. we don't necessarily need separate visual identity for each, but if you see a way to do it, that would be cool

**Comment by akrych** [comment]
Some other ideas: 

![ipfs_conf](https://user-images.githubusercontent.com/22168118/40661066-19149da8-6353-11e8-8478-7e8685252920.png)
