### ISSUE TITLE
Finalize IPFS website content and information architecture

### ISSUE THREAD

**Issue by meiqimichelle** [ipfs/conf#34]
We started with [several](https://docs.google.com/document/d/1pjik41wpK2FjlB5kyHKyGGz0o6yAMGJwOtspElXbZTI/edit#) [documents](https://docs.google.com/document/d/1X2HKFq_4xy0wGnlgL_NzqeC_exHTHx6YvpxmNUftguk/edit) and notes in issues around content and information architecture for the conference website. I'm consolidating those discussions here so we can align and finalize.

@flyingzumwalt nicely summarized the desired approach to the pieces of content (and by extension, their logos) on the IPFS Conf website [here in our new visual identity issue](https://github.com/ipfs/conference/issues/33) (emphasis my own):

> If we have separate logos for the Conf and the Developer Meetings, the Conf should be the dominant identity that catches people's attention. By contrast, the Developers Meetings will be the understated, practical, "internal" event so the branding should be understated too. **For example, the website will have info about both events, but will feature the Conf much more prominently while requiring people to specifically seek out info about the Developers Meeting.**

**As this is the case, a potential information architecture is as follows, with v2 draft content for [the homepage in this doc](https://docs.google.com/document/d/1GnjEdUrqJ7OidAIWBsIjQM-GIabjVaqhBijwrzpPrBA/edit#), and v2 draft content for [the community/dev meeting page in this doc](https://docs.google.com/document/d/1Qg5LcFHqhvRxyjOKdy9I54umR9wOhX2yBqHfQN0iP0M/edit#).**

<img width="593" alt="screenshot 2018-05-22 20 15 25" src="https://user-images.githubusercontent.com/4827522/40385330-1deb45d4-5dfe-11e8-9846-c54cdb97131c.png">

<img width="593" alt="screenshot 2018-05-22 20 15 36" src="https://user-images.githubusercontent.com/4827522/40385340-29daee9e-5dfe-11e8-8b61-94fd50307cbf.png">

## What I'd like feedback on
- Does this information architecture make sense? _Please read the [v2 copy docs](https://drive.google.com/drive/folders/1atFXHazZhe0ACfFLG7s2u49NfNsveeOh) in addition to looking at the above images to understand how this might fit together._
- Does the messaging relatively make sense? That is, there is still copy-editing and wordsmithing that should be done, but if the general arch of the story conveys what we're looking for, I'd like to get agreement on that so design work can move forward.

**Comment by mgoelzer** [comment]
I left feedback in the docs for libp2p stuff.  Overall, looks great!
