### ISSUE TITLE
IPFS Conf presentation proposals: Where and How?

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conf#35]
_This is for IPFS Conf in November, not the Dev Meetings in July. The related issues for the Dev Meetings are #12 and #24_

Where and how should we have people propose sessions for IPFS Conf? 

- What are some good reference examples of how other conferences have done that? 
- What timeline should we use for soliciting proposals, reviewing them, sending out acceptances, etc?
- How should we choose which proposals to accept?
- What should be the ramifications of having your proposal accepted? ie. Do you get a discount on your registration?

**Comment by diasdavid** [comment]
Let's close this one until the Dev Meetings are over.
