### ISSUE TITLE
Event Registration

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conf#38]
Decide how we will handle registrations, how we will accept payments, and what information we need to gather at registration -- tshirt sizes, arrival/departure dates, which hotel they will stay at, whether they have dietary constraints, etc. We should gather all of this information at once when they register.

- [ ] Decide which platform to use for registration and payment (Eventbrite, brown paper tickets, google forms, etc)
- [ ] Identify the information we need to collect on registration (tshirt sizes, arrival/departure dates, which hotel they will stay at, whether they have dietary constraints, etc.)

**Comment by mgoelzer** [comment]
This seems like a pretty list.  Glad you thought of T-shirt size.  

The only ones I have doubts about about are arrival/departure and hotel.  Why do we need this information?  (For PL Team/Core, I agree we need it.)  Also, attendees may complete the registration form before they have booked flights and hotel.

**Comment by flyingzumwalt** [comment]
@jamiejn could you address the question of why you want arrival/departure dates and info about who's staying at which hotel?

I'm not sure about ti.to, but eventbrite lets you edit your answers after registering, so people could fill in the info later. So it's technically feasible, but I'm not sure if we actually need it.

**Comment by jamiejn** [comment]
@flyingzumwalt  @mgoelzer  I would like to have arrival/departure dates mainly to have a total number of rooms that we need reserved in the blocks in each of the two hotels and on which dates to avoid cancellation fees and reserving unnecessary rooms, (especially if we expect the number of rooms will change if people leave on Wednesday.) This would also be a big help to calculate catering needs at the venue and for the Wednesday evening event.
 
I'm adding more hotel room block details/updates issue #3 

If we use a software that allows people to edit answers later, that would be good but I'm not sure how many people will go back and add in their travel dates after they've already completed the registration form.

**Comment by flyingzumwalt** [comment]
As far as tools, @diasdavid has enthusiastically suggested using https://ti.to/ -- that sounds good to me. I've never used it.

**Comment by meiqimichelle** [comment]
NB: getting an account set up in https://ti.to/ is being tracked [in this issue](https://github.com/protocol/2018-dev-meetings-berlin/issues/11#issuecomment-393905162)

**Comment by diasdavid** [comment]
The platform has been picked: tito.io ⭐️
We will post the registrations urls soon and announce it through the IPFS All Hands and respective repos:
- https://github.com/ipfs/developer-meetings
- https://github.com/libp2p/developer-meetings
