### ISSUE TITLE
Link to pre-register is not found

### ISSUE THREAD

**Issue by danielarmengolaltayo** [ipfs/conf#55]
Dynamic Link Not Found

Short URL (https://goo.gl/forms/0Pu6VZzG8pRAmrrv2) not found

If you are the developer of this app, ensure that your Dynamic Links domain is correctly configured and that the path component of this URL is valid.

**Comment by hsanjuan** [comment]
Thanks. This repository is for something that has not come to happen or launch yet. I will disable it for the moment.
